"""Initial revision

Revision ID: 9b4a6483c1e8
Revises:
Create Date: 2020-08-29 13:39:19.766359

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9b4a6483c1e8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("users_pkey")),
        sa.UniqueConstraint("username", name=op.f("users_username_key")),
    )
    op.create_index(op.f("users_id_idx"), "users", ["id"], unique=False)
    op.create_table(
        "offers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("offers_user_id_users_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("offers_pkey")),
    )
    op.create_index(op.f("offers_id_idx"), "offers", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("offers_id_idx"), table_name="offers")
    op.drop_table("offers")
    op.drop_index(op.f("users_id_idx"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
